import 'package:barilan/flame_game/component/player.dart';
import 'package:flame/components.dart';
import 'package:flame/input.dart';
import 'package:flutter/material.dart';

class JumpButton extends HudButtonComponent {
  JumpButton(this.player)
    : super(
        button: RectangleComponent(
          size: Vector2.all(120),
          paint: Paint()..color = Colors.blue,
        ),
        margin: const EdgeInsets.only(bottom: 20, right: 300),
        // position: Vector2(120, 400), // Adjust for button placement
        onPressed: () {
          player.jump();
          print("Im clicked");
        },
      );

  final Player player;
}

class LeftButton extends HudButtonComponent {
  LeftButton(this.player)
    : super(
        button: RectangleComponent(
          size: Vector2.all(120),
          paint: Paint()..color = Colors.blue,
        ),
        margin: const EdgeInsets.only(bottom: 20, left: 300),
        // position: Vector2(120, 400), // Adjust for button placement
        onPressed: () => player.startRun('left'),
        onReleased: () => player.stopRun(),
        onCancelled: () => player.stopRun(),
      );

  final Player player;
}

//generated by ai
// class LeftButton extends HudButtonComponent {
//   LeftButton(this.player)
//     : super(
//         button: RectangleComponent(
//           size: Vector2(80, 80), // Adjust size for better UI
//           paint:
//               Paint()
//                 ..shader = LinearGradient(
//                   colors: [Colors.blue.shade700, Colors.blue.shade400],
//                   begin: Alignment.topLeft,
//                   end: Alignment.bottomRight,
//                 ).createShader(Rect.fromLTWH(0, 0, 80, 80)),
//           children: [
//             // Add an icon or text
//             TextComponent(
//               text: "←",
//               position: Vector2(25, 20),
//               textRenderer: TextPaint(
//                 style: TextStyle(
//                   color: Colors.white,
//                   fontSize: 40,
//                   fontWeight: FontWeight.bold,
//                 ),
//               ),
//             ),
//           ],
//         ),
//         margin: const EdgeInsets.only(bottom: 20, left: 20),
//         onPressed: () => player.startRun('left'),
//         onReleased: () => player.stopRun(),
//         onCancelled: () => player.stopRun(),
//       );

//   final Player player;
// }

//image button
// import 'package:flame/components.dart';
// import 'package:flame/input.dart';
// import 'package:flame/flame.dart';
// import 'package:flutter/material.dart';

// class LeftButton extends SpriteButtonComponent {
//   LeftButton(this.player)
//       : super(
//           sprite: Sprite(Flame.images.fromCache('left_button.png')),
//           pressedSprite: Sprite(Flame.images.fromCache('left_button_pressed.png')),
//           size: Vector2.all(80),
//           position: Vector2(50, 500), // Adjust for better placement
//           onPressed: () => player.startRun('left'),
//           onReleased: () => player.stopRun(),
//         );

//   final Player player;
// }

class RightButton extends HudButtonComponent {
  RightButton(this.player)
    : super(
        button: RectangleComponent(
          size: Vector2.all(120),
          paint: Paint()..color = Colors.blue,
        ),
        margin: const EdgeInsets.only(bottom: 20, left: 100),
        // position: Vector2(120, 400), // Adjust for button placement
        onPressed: () => player.startRun('right'),
        onReleased: () => player.stopRun(),
        onCancelled: () => player.stopRun(),
      );

  final Player player;
}

class FireButton extends HudButtonComponent {
  FireButton(this.player)
    : super(
        button: RectangleComponent(
          size: Vector2.all(120),
          paint: Paint()..color = Colors.red,
        ),
        margin: const EdgeInsets.only(bottom: 20, right: 200),
        // position: Vector2(120, 400), // Adjust for button placement
        onPressed: () {
          player.fire();
          print("Im clicked");
        },
      );

  final Player player;
}
